### PR TITLE
Foundation 6.3.0

### PR DESCRIPTION
**Pull request by Sean-BREI**
Updated _bower.json

### CODE REVIEW

**Comment by nessthehero** [comment]
@Sean-BREI There are conflicts in generators/new/index.js. Please fix these.

**Comment by Sean-BREI** [comment]
Fixed conflicts.

**Comment by nessthehero** [comment]
Can you bump the version 3.2.4 in package.json?

Sorry.

**Comment by Sean-BREI** [comment]
Done.

**Comment by Sean-BREI** [comment]
Ok, try again.

**Pull request closed without merging**
